### ISSUE TITLE
Set up a Discourse forum for comments and discussions

### ISSUE THREAD

**Issue by amirmc** [Unikernel-Systems/unikernel.org#25]
I've been looking at ways we can communicate across projects. In the case of unikernel.org, some of the projects already have their own vibrant mailing lists. Asking those members to engage with and contribute to another email list can feel like a burden, hence I've been considering other options (i.e. alternatives to mailing lists).

Rust seems to have done quite well by using [Discourse](http://www.discourse.org) for both its [user](https://users.rust-lang.org) and [dev](https://internals.rust-lang.org) groups. In fact they explicitly, [deprecated their dev mailing list](https://mail.mozilla.org/pipermail/rust-dev/2015-January/011558.html) in favour of the forum software (and other online locations).

Although there are differences between forum-style software and email, it seems that Discourse can replace much of what email offers with minimal downside (see their [meta-discussion](https://meta.discourse.org/t/can-discourse-replace-mailing-lists/10888) on the topic and their [about](http://www.discourse.org/about/) section).  

Given this, I think it's worth trying out Discourse for unikernel.org.  Following the Rust discussions (and others), I think it would be useful to _(eventually)_ allow for two forums — one for unikernel devs/internals and another for unikernel users.

Initially, I think we should start with just one that's primarily for devs — of course, user questions will be welcome, but as those grow in volume, the intent would be to create a separate forum for them.

The next step would be to get an instance up and running somewhere and make sure that email is hooked up appropriately.  We can either do this ourselves or go with the hosted option:
- _Self-install_ — The [install instructions](https://github.com/discourse/discourse/blob/master/docs/INSTALL.md) mention that the Docker images are supported, though I expect that email might be more tricky to set up.
- _Hosted_ — Pay Discourse $100 a month. Can always move to a self-installed version later.  I'm quite tempted by this as it means the site is up and running quickly (as long as I can find $100 per month!).

**Comment by amirmc** [comment]
This would also have the benefit of acting as a comment system for blog posts (see [boingboing.net](http://boingboing.net) for examples).

**Comment by amirmc** [comment]
I'd be keen to get thoughts/opinions on the above from some of the existing unikernel devs.  cc @avsm @alfred-bratterud @acw @mor1 @samoht @mato @justincormack 

I know there are many other people but I didn't want to tag-spam everyone.
Please do feel free to comment if you have thoughts!

**Comment by avsm** [comment]
I'm in favour of Discourse. Can the hosted one be converted to a self hosted one later with the data expired?

**Comment by acw** [comment]
Seems reasonable to me. It'd be nice to have a single place to host and discuss some of the tools, tips, and tricks that are going to be common across all our projects. I know we've all lost a lot of time repeating each other's work in the past, and it'd be nice not to continue that trend for too long ...

**Comment by alfreb** [comment]
Discourse looks good, nice job @amirmc. Since there are (potential) expenses attached it might be an indication that a more formalized organization could be desirable in the future. IEEE / ACM subcommittee on unikernels? Or is that just asking for admin work? :-)

**Comment by mato** [comment]
Regarding having a place for general cross-project unikernel discussion, yes please, good idea!

If the intent in the medium-term is for low volume cross-project _development_ discussion, then personally I'd prefer a classic mailing list. It's trivial (and free) to set one up at e.g. freelists.org. Having said that, if the majority are in favour of Discourse, and you think it's worth $100/month, go for it.

**Comment by mor1** [comment]
Happy to try discourse. Would like it if there was a way to read it that didn't involve remembering to check (and keep open) yet another browser tab, as well as giving up sync on read state between devices. (Something that email mostly can manage.) But I agree that the archiving/searching/threading faciltiies in most email systems suck, so worth a try... :)

**Comment by amirmc** [comment]
Hi folks, Thanks for the comments!  Some quick responses:
- @avsm: yes the data can be exported so we can move to a self-hosted version later. This [walkthrough](https://meta.discourse.org/t/move-your-discourse-instance-to-a-different-server/15721) should help when the time comes.
- @alfred-bratterud: There's a free 14 day trial and after that, I'm happy to put it on my card and figure out the details later. It shouldn't be too difficult to add to the list of existing paid infrastructure (e.g. the machines that serve the [MirageOS website](https://mirage.io) and the unikernel.org domain itself). 
- @mato, @mor1: Email interaction is a _critical_ feature for us (and was the first thing I checked up on).  You should be able to interact with Discourse almost entirely through email if you wish, similarly to GitHub Issues.  There is even a setting where we can allow _new_ threads to be started by incoming email (though, I'm a little wary of turning this on without some testing).  This should allow the best of both worlds — interaction by email but also a fully featured website with good search capability and archives. The [about](https://www.discourse.org/about/) page has quick summaries of such features, which I found really helpful when assessing this.

I'll go ahead and set up a hosted version of Discourse. Unless there's any objection (or a better suggestion), I'll set things up to use the subdomain `dev.unikernel.org`.

**Comment by amirmc** [comment]
I asked a few people about the specific URL and after some thought, decided that we should go with `devel.unikernel.org` (i.e. `devel` usually implies 'development'). This is a little bit clearer about purpose and also matches up with existing mailing list conventions (e.g. `halvm-devel@...` and `mirageos-devel@...`)

For the sake of clarity (and documenting it somewhere public), the reason we might eventually need _two_ discourse forums is because they're flat forums i.e. one 'board' per URL.  I realise this may not have been clear, since a (reasonable) assumption about 'forums' is the ability to have sub-boards. Discourse doesn't offer 'sub-boards' (just categories), which is why we'll need one instance for development (`devel.unikernel.org`) and eventually another one for users (`users.unikernel.org`) — and is also why I wanted to take some care over naming :)

@avsm has set up the DNS for `devel.unikernel.org` so I'll close this issue when that propagates and there's something to point at.

**Comment by amirmc** [comment]
Hi folks, the site is now live at [devel.unikernel.org](http://devel.unikernel.org) but there's additional work to do regarding the email setup. I've opened a separate issue to track that (see #26).

**Comment by amirmc** [comment]
Email interaction now works and SSL has been enabled.  Please do sign up on the site via the login link!
