### ISSUE TITLE
Set up email interaction for devel.unikernel.org

### ISSUE THREAD

**Issue by amirmc** [Unikernel-Systems/unikernel.org#26]
As part of the set-up for the discourse forum (see #25 and [devel.unikernel.org](http://devel.unikernel.org)), I need to ensure that email interaction works as expected.  This isn't quite as 'plug-and-play' as I'd hoped so I'm trying to take care that it works properly before asking anyone to sign up to the site (I've locked sign up - if you want access anyway, let me know).

The [discourse docs](https://meta.discourse.org/t/meta-documentation-table-of-contents/32240) should help with this and some particularly relevant topics are:
- [Configure your domain for Discourse hosted email](https://meta.discourse.org/t/configure-your-domain-for-discourse-hosted-email/14177)
- [Set up reply via email support](https://meta.discourse.org/t/set-up-reply-via-email-support/14003)

I'll be looking over these docs over the coming couple of days to make sure I've understood what's needed.  Any help is welcome! :)

cc @avsm as this may involve additional DNS records (apologies for the extra work).

**Comment by amirmc** [comment]
I also left a [pinned post](http://devel.unikernel.org/t/sign-up-is-closed-until-email-support-is-complete/14) referencing this issue in case anyone does find their way to the site.

If anyone wants to sign up to the site without full email support, that's completely fine (just comment here)!  You will get email _notifications_ but will have to visit the site to respond.:)

**Comment by SamSaffron** [comment]
if you can wait till monday we can set something up for you, we plan on auto provisioning something like unikernel@mail.discourse.org account automatically for mail support (if you prefer to control the email it is fine)

We are also working at the moment on more improvements to the mailing list support so keep feedback coming.

**Comment by amirmc** [comment]
That would be great, thanks! Monday would be fine :)

Where's the best place to send feedback to you?

Best wishes,
Amir

## 

Sent via mobile

**Comment by amirmc** [comment]
I just found my way to the '[MOSS roadmap](https://meta.discourse.org/t/moss-roadmap-mailing-lists/36432)' so I'll leave email-related comments there — very pleased to see this :)

For others following this issue, Mozilla awarded a grant to _"... enhance Discourse with several individual-but-related features that will make the software easier to use via e-mail ... With all assignments successfully completed, Discourse will be on-par-with or surpass the feature set of mailing list programs such as GNU Mailman or PHPlist."_

**Comment by avsm** [comment]
I've added in the TXT records for `unikernel.org`.  I'm not quite sure what the SPF setup should like though, since it seems to be for `unikernel.org` which doesn't currently have any MX setup.  Don't we need to point the `MX` to the hosted discourse servers as well to receive the replies?

**Comment by SamSaffron** [comment]
can you email team at discourse.org and we can help you out?

On Sat, Dec 26, 2015 at 4:51 AM, Anil Madhavapeddy <notifications@github.com

**Comment by amirmc** [comment]
Hi @SamSaffron, were you able to set up the mail support you mentioned?

Also, Happy New Year! We’ve got a few more hours before it’s our turn ;)

**Comment by SamSaffron** [comment]
Sure we can set it up for you on Australia Monday can you email team<at>
discourse.org so we can track it internally ?

**Comment by amirmc** [comment]
Done! :)

## 

Sent via mobile

**Comment by avsm** [comment]
Just checking in here -- if there's something i need to do with MX records just let me know :)

**Comment by amirmc** [comment]
Email interaction appears to be working now and I’ve tested it out.

I’ve opened up signup to the forum but haven’t mentioned it widely as I’m populating content first.

**Comment by amirmc** [comment]
Since email replies appear to be working fine, I'm closing this issue
