### ISSUE TITLE
"please do not cite or redistribute"

### ISSUE THREAD

**Issue by hannesm** [Unikernel-Systems/unikernel.org#32]
it would be great if you could make screenshots of the final papers... (I browsed on my mobile phone, and this leaped to the eye)
http://unikernel.org/files/2015-nqsbtls-usenixsec.png http://unikernel.org/files/2015-sibylfs-sosp.png

maybe others as well?  also a link to the specific project website would be nice to give some credit to the projects&authors.

**Comment by amirmc** [comment]
Yes, there are several that have out of date thumbnails. 

We can add links in the descriptions. If you've got suggestions for any of them, please feel free to submit a PR :)

Best wishes,
Amir

## 

Sent via mobile

**Comment by hannesm** [comment]
sorry. I have neither time nor energy to care about yet another website. just wanted to point out the pieces I'm really unhappy with.

**Comment by avsm** [comment]
I'll update these

**Comment by amirmc** [comment]
I've now fixed this and also made them clicky (in https://github.com/Unikernel-Systems/unikernel.org/commit/2e2ac68bb9976d75878b62da5cb11647ec2487d3)

**Comment by amirmc** [comment]
And also a link to the nqsb site (https://github.com/Unikernel-Systems/unikernel.org/commit/fa1f7888142edeb1b1ec8b82d98685f5b1f2eaf7).  :)
